### PR TITLE
Update requirements.rst

### PR DESCRIPTION
**Pull request by denniel-sadian**
Missing space.

### CODE REVIEW

**Comment by RDIL** [comment]
After Travis CI build passes it will be ready for merge.

**Comment by RDIL** [comment]
Please fix the build.

**Comment by Flimm** [comment]
Sometimes Travis CI fails with connection errors. I reran the test and it worked. PR is merged.

**Comment by Flimm** [comment]
@RDIL By the way, to trigger a Travis CI rebuild, you can just log in to Travis CI and click the appropriate button. The button should be visible if you're a member of Jazzband. You don't need to push a new commit.

**Comment by RDIL** [comment]
Yeah I know, just didn’t have access to the Travis website as I was in school.

**Pull request merged**
