### PR TITLE
Deprecate Python 2 compatibility shims

### PR DESCRIPTION
**Pull request by aleksihakli**
Drop Python 2 compatibility shims and make codebase Python 3 only.

This PR reduces complexity and makes the code more understandable and maintainable in the long run.

### CODE REVIEW

**Comment by camilonova** [comment]
@aleksihakli can you please check the travis output?

**Comment by aleksihakli** [comment]
@camilonova yeah the patch is not yet complete. I started working on this on the weekend and didn't have time to finish all the changes :) I'll fix it and notify you afterwards.

**Comment by aleksihakli** [comment]
@camilonova the Python 2 deprecation PR is ready for upstreaming now.

**Comment by aleksihakli** [comment]
Seems like networking errors in Travis produce false negatives, retriggering builds to provide more feedback.

**Pull request merged**
