### PR TITLE
Fixes #691 - Obsolete THUMBNAIL_KVSTORE

### LINKED ISSUE #691: Obsolete THUMBNAIL_KVSTORE
I think that the configurable KVStore adds complexity to the project without real added value, all the more that now Django also includes a Redis cache backend in core. What about only keeping ``THUMBNAIL_CACHE`` to point to some Django-configured cache and tell users to do the cache configuration at the Django project level? 

Are there still use cases to implement/specify custom KVStores that are not possible as Django cache backends?

@camilonova, would love to get your input on this idea.

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Please just wait a bit before reviewing this patch, there are some things I'd want to check before going forward.

**Comment by uri-rodberg** [comment]
> Please just wait a bit before reviewing this patch, there are some things I'd want to check before going forward.

@claudep Convert this PR to draft? It's from 2022.

**Comment by dulmandakh** [comment]
@claudep Django 3.x is no longer maintained, so we only have Django versions that supports Redis cache. Removing non-supported Django versions in https://github.com/jazzband/sorl-thumbnail/pull/754.

How I can help with this PR?

**Comment by dulmandakh** [comment]
@claudep how about remove the support without deprecating and release major release which a few breaking changes 😉

**Comment by claudep** [comment]
I think we can release a 12.x version with the deprecation, and not so long after release a 13.x version with the removals.

**Review by dulmandakh — APPROVED** [review]
LGTM

**Comment by dulmandakh** [comment]
@claudep may I merge this PR, it looks good to me.

**Comment by claudep** [comment]
Thanks for the review!

**Pull request merged**
