### PR TITLE
pyproject.toml: add optional dependencies

### PR DESCRIPTION
**Pull request by dulmandakh**
This PR adds support for installing with optional dependencies. Fixes https://github.com/jazzband/sorl-thumbnail/issues/684

### CODE REVIEW

**Comment by claudep** [comment]
Looks good, however I think this deserves a note somewhere in the documentation, probably in installation.rst.

**Comment by dulmandakh** [comment]
> Looks good, however I think this deserves a note somewhere in the documentation, probably in installation.rst.

I tried to write some, but couldn't finish due to my language skills.

**Comment by dulmandakh** [comment]
@claudep could you please help with the documentation

**Comment by claudep** [comment]
I did not forget you and will return to this as soon as time permits, thanks for your patience!

**Comment by claudep** [comment]
I suggest installing this patch:
```
diff --git a/docs/installation.rst b/docs/installation.rst
index 9402faa..4f87538 100644
--- a/docs/installation.rst
+++ b/docs/installation.rst
@@ -5,11 +5,15 @@ Installation & Setup
 Installation
 ============
 First you need to make sure to read the :doc:`requirements`. To install
-sorl-thumbnail is easy::
+sorl-thumbnail::
 
     pip install sorl-thumbnail
 
-Or you can go to `the github page <https://github.com/sorl/sorl-thumbnail>`_
+Depending of the chosen image backend, you may also use one of::
+
+    pip install sorl-thumbnail[pil]
+    pip install sorl-thumbnail[wand]
+    pip install sorl-thumbnail[pgmagick]
 
 Setup
 =====
```

**Comment by dulmandakh** [comment]
@claudep added documentation changes per your suggestion. thank you

**Comment by claudep** [comment]
Thanks great! I have still one question. Shouldn't we name the optional dependency `imgmagick` or `imagemagick` instead of `wand`? Of course, behind the scene, we're still installing the `wand` lib.

**Comment by dulmandakh** [comment]
IIRC, there is another backend for imagemagick.

**Comment by claudep** [comment]
Ah yes, you're right.

**Review by claudep — APPROVED** [review]
:+1:

**Pull request merged**
