### PR TITLE
Modernise Python syntax

### PR DESCRIPTION
**Pull request by smithdc1**

### CODE REVIEW

**Comment by claudep** [comment]
You may also address `super(...)` calls?

**Comment by smithdc1** [comment]
Yup. Let me do that as well.

**Comment by smithdc1** [comment]
@claudep on the topic of maintenance, would a PR to drop Django 1.1 support be welcomed? I'd replace Django 1.1 with Django 3.1 which is currently untested. I suspect dropping Django 1.1 will help simplify a few other topics such as the URL() change. I'd also happy to investigate these.

**Comment by smithdc1** [comment]
The test failure looks like a Travis time out on a single scenario rather than anything wrong with this?

**Comment by claudep** [comment]
Absolutely, the test failures are network-related and IMHO a bug in itself. Network access should be mocked for tests with URL image sources (`Image('http...')`).

**Pull request merged**
