### PR TITLE
fixed DeprecationWarning

### PR DESCRIPTION
**Pull request by LarryMartell**
Fixed DeprecationWarning from setuptools 67.5.0 and above (issue #727)

### CODE REVIEW

**Comment by uri-rodberg** [comment]
Do you know why tests failed or canceled?

**Comment by claudep** [comment]
Now that Python 3.7 is EOL, we should remove support/testing for it. By the way, #735 is fixing the test issues.

**Comment by uri-rodberg** [comment]
@LarryMartell Can you rebase your PR on branch master?

**Comment by LarryMartell** [comment]
> @LarryMartell Can you rebase your PR on branch master?

Done

**Comment by uri-rodberg** [comment]
@LarryMartell Tests are not successful, please fix. Also, I don't see that these commits are rebased. It should not contain the commit 7e866234b78b74a81674c2a31f4490a474c779de. Please try to rebase without this commit. If it doesn't work, please create a new PR with your commits only and without 7e866234b78b74a81674c2a31f4490a474c779de.

**Comment by LarryMartell** [comment]
> [7e86623](https://github.com/jazzband/sorl-thumbnail/commit/7e866234b78b74a81674c2a31f4490a474c779de).

The tests fail in master and then in all the other branches for the same reason. I have a fix for that and am testing it now. Once that is in master and then merged down to this branch it should pass. 

As far as the rebase goes, I'm a bit confused. If I look at that commit it shows: 

`This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
`
I synced master in my fork from jazzband and then rebased this branch with that.

**Comment by LarryMartell** [comment]
The tests passed in my fork in my test-fixes branch. Just raised a PR for that.

**Comment by uri-rodberg** [comment]
@LarryMartell Please create a new PR with the relevant commit or commits. I'm closing this PR.

**Pull request closed without merging**
