### PR TITLE
Feature/travis container

### PR DESCRIPTION
**Pull request by haakenlid**
Issue #410 

I don't expect this to work on the first try. Container based Travis does not support regular `sudo apt-get`, but you can use `addons.apt.packages` instead. 
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#How-do-I-install-APT-sources-and-packages%3F

### CODE REVIEW

**Comment by mariocesar** [comment]
Thanks, I had been postponing this for a while, we got a pretty big list of environment to tests and it is slow to test changes are right

**Comment by haakenlid** [comment]
Looks like it's not quite ready yet. I'm having trouble installing all the required apt packages.
I've registered my own fork on Travis, and will submit a new pull request here if I get it working properly. 
https://travis-ci.org/haakenlid/sorl-thumbnail/

**Comment by haakenlid** [comment]
I've removed some apt dependencies that were confliciting. It doesn't seem like it's possible to use different apt dependencies for each test run, so I had to do some trial and error before getting a config that seems to be working.

**Comment by haakenlid** [comment]
The build is passing, but for now it looks like it's significantly slower than the old CI. Looking at the logs, using Travis caching seems to slow things down a lot.  [In this example `store build cache` takes more time than running the test suite](https://travis-ci.org/mariocesar/sorl-thumbnail/jobs/84331563#L318)

**Comment by haakenlid** [comment]
The travis tests for this PR are stuck, and I think they have to be restarted manually. Probably caused by a recent outage at Travis.  https://www.traviscistatus.com/incidents/frn0nyd2jhq7

**Comment by camilonova** [comment]
@haakenlid sorry for the delay. I would like to merge this ASAP. Can you please review and update your changes?

**Comment by haakenlid** [comment]
I'll try to resolve it. But it's two years ago that I made the pull request, so it's not i fresh memory. :)

**Comment by haakenlid** [comment]
I will close this, since my pull request is so much out of sync with upstream.

**Pull request closed without merging**
