### PR TITLE
Re-add Python 3.4 and 3.5 definitions

### PR DESCRIPTION
**Pull request by benjaoming**
Suggesting to merge this and tag 12.6.1

CC: @aleksihakli @camilonova @jezdez

### CODE REVIEW

**Comment by jezdez** [comment]
https://github.com/jazzband/sorl-thumbnail/blob/8673a9188734d5c572e8197bd633f3272f9c88d3/setup.py#L25 needs to be defused a bit for this to work.

**Comment by benjaoming** [comment]
Thanks @jezdez - I absolutely missed that!

**Comment by benjaoming** [comment]
> If you want to support 3.4 and 3.5 it's good to have them in the Travis and tox test matrix as well :)

@aleksihakli I've used the PR description from #610 in the changelog to state that these versions are deprecated.

**Comment by aleksihakli** [comment]
Ah, that seems good! The codebase didn't change anyways so things should ideally be good to go.

**Comment by aleksihakli** [comment]
By the way, merging this and making a new release on GitHub tag GUI from master should now push the changes to the Jazzband PyPI server after a successful build. From there they can be then released to public PyPI :)

**Comment by benjaoming** [comment]
@camilonova @aleksihakli - I'm not a band member (might be some day) - but I can vouch for a 12.6.1 tag :)

**Comment by aleksihakli** [comment]
@camilonova I added a 12.6.1 tag, would you like to make a new release?

@jezdez I can also help maintain the project and make new releases through the Jazzband site if @camilonova and the existing contributors are OK with that.

**Comment by camilonova** [comment]
@aleksihakli please do. I'm happy to bring you in. Go ahead and make the 12.6.1 release

**Comment by aleksihakli** [comment]
@camilonova I don't have the permissions to the project, so it would be great if you could make the release through the Jazzband site to PyPI!

**Comment by camilonova** [comment]
I've tried and got this:

```
Standard error

HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by aleksihakli** [comment]
@camilonova this was probably caused by a rST syntax error in the README.rst, merging #613 should help. We can bake a 12.6.2 release from that after upstreaming. I'll add a rST validator step into the CI pipeline.

**Comment by camilonova** [comment]
@aleksihakli just merged #613 let's go for a release

**Pull request merged**
