### PR TITLE
12.6.0 release

### LINKED ISSUE #601: Support Django 3.0
This line does not work with Django 3.0:

`from django.utils.encoding import python_2_unicode_compatible`

https://docs.djangoproject.com/en/3.0/releases/3.0/

You can import directly from six if you still need to support Python 2.

### PR DESCRIPTION
**Pull request by benjaoming**
Superseding #604 - fixes #601

As I open the PR, @camilonova (seemingly the only responsive maintainer) can approve and merge the PR.

As #604 was opened by @camilonova, it requires a second person with write access.

### CODE REVIEW

**Comment by inoks** [comment]
@camilonova Can you please approve and merge PR?

**Comment by inoks** [comment]
Hey @sorl , @mariocesar, @relekang, @Flimm, @benjaoming!

Can you please review and merge that PR?

**Comment by benjaoming** [comment]
@inoks please don't spam like this. If you cared to read the text of this PR, you would even see that I cannot merge it.

**Comment by camilonova** [comment]
Thank you

**Comment by benjaoming** [comment]
Great @camilonova - how is the procedure for releasing on PyPI?

**Pull request merged**
