### PR TITLE
 Fix #554: Fix AdminImageWidget with Django 2.1

### LINKED ISSUE #554: AdminImageWidget render exception in django 2.1
class AdminImageWidget render function does not accept a renderer input parameter, which is used in django2.1.
This causes an exception if you use a sorl picture field in the django admin.

### PR DESCRIPTION
**Pull request by haakenlid**
From the django 2.1 release notes:
> Support for Widget.render() methods without the renderer argument is removed.

With Django 2.1 the current widget will raise this exception:
> TypeError: render() got an unexpected keyword argument 'renderer'

### CODE REVIEW

**Comment by timgraham** [comment]
Could you add a test?

**Comment by haakenlid** [comment]
Are there any tests for the admin widgets at all? I'm not familiar enough with the project to know where to add such a test.

**Comment by timgraham** [comment]
Me neither, but it shouldn't be difficult to look or grep around.

**Comment by timgraham** [comment]
I added a test.

**Pull request merged**
