### PR TITLE
Delete old thumbnails from the media/cache directory and the database

### PR DESCRIPTION
**Pull request by LarryMartell**
Address issue [#721](https://github.com/jazzband/sorl-thumbnail/issues/721)

### CODE REVIEW

**Comment by uri-rodberg** [comment]
Do you know why tests failed or canceled?

**Comment by uri-rodberg** [comment]
@LarryMartell Can you rebase your PR on branch master?

**Comment by LarryMartell** [comment]
> @LarryMartell Can you rebase your PR on branch master?

Done

**Comment by uri-rodberg** [comment]
Please wait with this PR and don't do anything until we finish merging #737.

**Comment by uri-rodberg** [comment]
@LarryMartell Please contact me by email. Your mailbox is full.

**Comment by uri-rodberg** [comment]
I'm closing this PR. There is a new PR - https://github.com/jazzband/sorl-thumbnail/pull/740.

**Pull request closed without merging**
