### PR TITLE
Use container based travis build

### PR DESCRIPTION
**Pull request by haakenlid**
Updated version of pull request #411 for issue #410

### CODE REVIEW

**Comment by haakenlid** [comment]
The build stalls when trying to install pgmagick. Possibly related to this:
https://github.com/hhatto/pgmagick/issues/32

**Comment by haakenlid** [comment]
The tests are passing, but only after I disabled the pgmagick tests and the linting. 

I think it should be possible to speed up the travis tests by tweaking the travis and tox configs, but I'm not prepared to figure that out. Trying to use caching for pip as documented by travis doesn't seem to have any effect. The coverage integration also seems to have a bug.

The test duration is 10 min 12 sec, which I think is similar to the regular travis tests.

I didn't notice any delay between pushing to github and travis starting to run the tests. But I'm not if this delay is logged anywhere so I can't compare the startup time to the regular tests. According to the docs, it's supposed to be faster. 

https://docs.travis-ci.com/user/reference/trusty/#Container-based-with-sudo%3A-false

> The advantage of running with sudo: false is dramatically reduced time between commit push to GitHub and the start of a job on Travis CI, which works especially well when one’s average job duration is under 3 minutes.

**Comment by camilonova** [comment]
Thank you

**Comment by WhyNotHugo** [comment]
Was disabling flake8 accidental here?

**Comment by haakenlid** [comment]
No. With the flake8 step, every single tox test fails, since the code does not pass the linting. First make the code pass linting, then add linting to the CI. 

Also, it's good practice to have a single tox environment for linting (and one for coverage). That way you don't have to read through the travis ci logs to figure out if a test failed because of a regression, or simply because of a linting issue.

**Comment by haakenlid** [comment]
But I guess there could be reasons why you would like the CI tests on master to be red instead of green. I'm not claiming any strong ownership here, so feel free to reverse this merge if you disagree.

**Comment by camilonova** [comment]
I agree. Linting issues should be somewhere else.

**Pull request merged**
